-- Table: public.customers

-- DROP TABLE IF EXISTS public.customers;

CREATE TABLE IF NOT EXISTS public.customers
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    contact_info character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT customers_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.customers
    OWNER to postgres;

-- Table: public.employees

-- DROP TABLE IF EXISTS public.employees;

CREATE TABLE IF NOT EXISTS public.employees
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default",
    "position" character varying(255) COLLATE pg_catalog."default",
    location_id bigint,
    CONSTRAINT employees_pkey PRIMARY KEY (id),
    CONSTRAINT fkirh0a5q2en4gkbayqhgfiwhs FOREIGN KEY (location_id)
        REFERENCES public.locations (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.employees
    OWNER to postgres;

-- Table: public.ingredients

-- DROP TABLE IF EXISTS public.ingredients;

CREATE TABLE IF NOT EXISTS public.ingredients
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default",
    type character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT ingredients_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.ingredients
    OWNER to postgres;

-- Table: public.locations

-- DROP TABLE IF EXISTS public.locations;

CREATE TABLE IF NOT EXISTS public.locations
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    address character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT locations_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.locations
    OWNER to postgres;

-- Table: public.order_sauces

-- DROP TABLE IF EXISTS public.order_sauces;

CREATE TABLE IF NOT EXISTS public.order_sauces
(
    order_id bigint NOT NULL,
    sauce_id bigint NOT NULL,
    CONSTRAINT order_sauces_pkey PRIMARY KEY (order_id, sauce_id),
    CONSTRAINT fkggcav2u5feoj5ktv4vka2yp59 FOREIGN KEY (sauce_id)
        REFERENCES public.sauce_positions (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fklhhmgdsrfby7p05iyw72csq67 FOREIGN KEY (order_id)
        REFERENCES public.orders (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.order_sauces
    OWNER to postgres;

-- Table: public.order_shawarmas

-- DROP TABLE IF EXISTS public.order_shawarmas;

CREATE TABLE IF NOT EXISTS public.order_shawarmas
(
    order_id bigint NOT NULL,
    shawarma_id bigint NOT NULL,
    CONSTRAINT order_shawarmas_pkey PRIMARY KEY (order_id, shawarma_id),
    CONSTRAINT fk6bd0kyi7clcqljvqyo9bifu83 FOREIGN KEY (order_id)
        REFERENCES public.orders (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkfm3xvfh64wslq0rlvhyry5v07 FOREIGN KEY (shawarma_id)
        REFERENCES public.shawarma_positions (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.order_shawarmas
    OWNER to postgres;


-- Table: public.orders

-- DROP TABLE IF EXISTS public.orders;

CREATE TABLE IF NOT EXISTS public.orders
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    order_time timestamp(6) without time zone,
    customer_id bigint,
    CONSTRAINT orders_pkey PRIMARY KEY (id),
    CONSTRAINT fkpxtb8awmi0dk6smoh2vp1litg FOREIGN KEY (customer_id)
        REFERENCES public.customers (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.orders
    OWNER to postgres;

-- Table: public.sauce_ingredients

-- DROP TABLE IF EXISTS public.sauce_ingredients;

CREATE TABLE IF NOT EXISTS public.sauce_ingredients
(
    sauce_id bigint NOT NULL,
    ingredient_id bigint NOT NULL,
    CONSTRAINT sauce_ingredients_pkey PRIMARY KEY (sauce_id, ingredient_id),
    CONSTRAINT fk8ty3efl1el3v6lguxr2a2rt9b FOREIGN KEY (ingredient_id)
        REFERENCES public.ingredients (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkqam4egkr2hqvmovl4wbdh8w9a FOREIGN KEY (sauce_id)
        REFERENCES public.sauce_positions (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.sauce_ingredients
    OWNER to postgres;

-- Table: public.sauce_positions

-- DROP TABLE IF EXISTS public.sauce_positions;

CREATE TABLE IF NOT EXISTS public.sauce_positions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default",
    price double precision,
    CONSTRAINT sauce_positions_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.sauce_positions
    OWNER to postgres;


-- Table: public.shawarma_ingredients

-- DROP TABLE IF EXISTS public.shawarma_ingredients;

CREATE TABLE IF NOT EXISTS public.shawarma_ingredients
(
    shawarma_id bigint NOT NULL,
    ingredient_id bigint NOT NULL,
    CONSTRAINT shawarma_ingredients_pkey PRIMARY KEY (shawarma_id, ingredient_id),
    CONSTRAINT fk1cjylxos7igotfl39ottuo8ds FOREIGN KEY (shawarma_id)
        REFERENCES public.shawarma_positions (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fknacduqw2mnnbubbupm7ulr0h5 FOREIGN KEY (ingredient_id)
        REFERENCES public.ingredients (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.shawarma_ingredients
    OWNER to postgres;

-- Table: public.shawarma_positions

-- DROP TABLE IF EXISTS public.shawarma_positions;

CREATE TABLE IF NOT EXISTS public.shawarma_positions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default",
    price double precision,
    CONSTRAINT shawarma_positions_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.shawarma_positions
    OWNER to postgres;

-- Table: public.supplier_ingredients

-- DROP TABLE IF EXISTS public.supplier_ingredients;

CREATE TABLE IF NOT EXISTS public.supplier_ingredients
(
    supplier_id bigint NOT NULL,
    ingredient_id bigint NOT NULL,
    CONSTRAINT supplier_ingredients_pkey PRIMARY KEY (supplier_id, ingredient_id),
    CONSTRAINT fk3bqc0ct0aovkwmmb68w2a5yoc FOREIGN KEY (ingredient_id)
        REFERENCES public.ingredients (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkp3vcmvtp9n2prte7vbrvmp4b5 FOREIGN KEY (supplier_id)
        REFERENCES public.suppliers (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.supplier_ingredients
    OWNER to postgres;

-- Table: public.suppliers

-- DROP TABLE IF EXISTS public.suppliers;

CREATE TABLE IF NOT EXISTS public.suppliers
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    contact_info character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT suppliers_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.suppliers
    OWNER to postgres;


